version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sekolah_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - sekolah-network

  db:
    image: postgres:15-alpine
    container_name: sekolah_db
    environment:
      - POSTGRES_USER=sekolah
      - POSTGRES_PASSWORD=sekolah_password
      - POSTGRES_DB=sekolah
    volumes:
      - sekolah-data:/var/libposgresql/data
    networks:
      - sekolah-network

volumes:
  sekolah-data:

networks:
  sekolah-network:
