spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sekolah
    username: adminSekolah
    password: passwordSekolah
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db/migration
